"""The C searches of warband/_native.c, built only with the compiled simulation (warband/fastsim.py)."""

from array import array
from collections.abc import Iterable

def find_path_grid(start: tuple[int, int], goal: tuple[int, int], blocked: bytes | bytearray, width: int, height: int,
                   max_expansions: int, /) -> list[tuple[int, int]]: ...
def find_work_path(start: tuple[int, int], goals: dict[tuple[int, int], float], blocked: bytes | bytearray,
                   width: int, height: int, /) -> list[tuple[int, int]] | None: ...
def distance_field(starts: Iterable[int], blocked: bytes | bytearray, width: int, height: int, /) -> list[float]: ...
def region_labels(blocked: bytes | bytearray, width: int, height: int, labels: array[int], /) -> int: ...
def nearest_in_region(labels: array[int], region: int, goal: tuple[int, int], width: int, /) -> tuple[int, int]: ...
