"""The C searches and grid painting of warband/_native.c, built only with the compiled simulation (warband/fastsim.py)."""

from array import array
from collections.abc import Callable, Iterable, Sequence

from warband.rules import Terrain

def find_path_grid(start: tuple[int, int], goal: tuple[int, int], blocked: bytes | bytearray, width: int, height: int,
                   max_expansions: int, /) -> list[tuple[int, int]]: ...
def find_work_path(start: tuple[int, int], goals: dict[tuple[int, int], float], blocked: bytes | bytearray,
                   width: int, height: int, /) -> list[tuple[int, int]] | None: ...
def distance_field(starts: Iterable[int], blocked: bytes | bytearray, width: int, height: int, out: array[float], /) -> None: ...
def choose_tree(start: tuple[int, int], trees: Sequence[int], loaded: Iterable[int], remembered: list[Terrain | None], marker: Terrain,
                field: Sequence[float], blocked: bytes | bytearray, reach: Sequence[tuple[int, int]], width: int, height: int, /) -> tuple[int, int] | None: ...
def region_labels(blocked: bytes | bytearray, width: int, height: int, labels: array[int], /) -> int: ...
def nearest_in_region(labels: array[int], region: int, goal: tuple[int, int], width: int, /) -> tuple[int, int]: ...
def stamp_discs(visible: bytearray, discs: Iterable[tuple[tuple[int, int], int]], width: int, height: int, /) -> None: ...
def or_into(target: bytearray, source: bytes | bytearray, /) -> None: ...
def stamp_threats(blocked: bytearray, units: Iterable[tuple[float, float, float]], width: int, height: int, /) -> None: ...
def any_lit(visible: bytes | bytearray, x: int, y: int, w: int, h: int, width: int, height: int, /) -> bool: ...
def stale_tiles(visible: bytes | bytearray, rows: list[list[Terrain]], remembered: list[Terrain | None], width: int, height: int, /) -> list[int]: ...
def site_search(ring: Sequence[tuple[float, int, int]], left: int, top: int, draw: Callable[[], float], *inputs: object) -> tuple[int, int] | None: ...
